### ISSUE TITLE
cs_userinfo - support group access

### ISSUE THREAD

**Issue by jameswritescode** [atheme/atheme-contrib-modules#28]
Currently for a user to use `/cs userinfo` they need to have access in the channel on their user, so if they have access via a group it is not recognized.

Also doesn't seem to support users access through `*!*@*` or `$registered`.

**Comment by darksis** [comment]
why in athemeserv is no have limit?

**Comment by siniStar7boy** [comment]
@darksis What are you referring to?  Are you referring to a Channel Limit feature or something else?  

And is it related to the user info module issue that you commented on, or a new request/issue?  Please clarify or open a new Issue/Feature Request..

**Comment by darksis** [comment]
Channel Limit is feature is good to athemeserv and i`m sorry but i dont know how i open a new issue
